language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=8563e4d2656021b3e48db9e12c4e5693c56f668234d0236e535a0e8ed8222c53"
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - 'node_modules'
